### ISSUE TITLE
REQUEST: class for MIN, MAX dates and the interval between them

### ISSUE THREAD

**Issue by paha77** [amsul/pickadate.js#195]
It would be awesome to have a class for the DIV of the MIN date of the picker, the MAX date of the picker and the interval between them.

Something like:

``` css
klass : {
    ...
    minday : prefix + 'day--min',
    minday : prefix + 'day--max',
    minmaxinterval : prefix + 'day--minmaxinterval',
    ...
}
```

and then:

``` html
<div data-pick="1370037600000" class="picker__day picker__day--infocus picker__day--disabled picker__day--min">1</div>
...
```

Right now the dates outside the min-max only get the disabled class but this is the same as I disable a day with the disable attribute.
