### ISSUE TITLE
Flickering of the outline/border of input field when switching between months

### ISSUE THREAD

**Issue by hacfi** [amsul/pickadate.js#5]
When switching between months the input field shortly loses focus because of the click event resulting in a short flickering. My suggestion is to highlight the input field by adding an additional class to it instead of using the current CSS Styling:

``` css
input[type=date]:focus,
input[type=text]:focus {
    outline: none;
    border-color: #0089ec;
}
```

I know that this is only part of the demo but for styling purposes the highlighting class might be useful. What do you think?
