### ISSUE TITLE
Hide days ?

### ISSUE THREAD

**Issue by barbuslex** [amsul/pickadate.js#671]
Hi,

Is it possible to hide some days from week in datepicker ?

Exemple: I want to display only working days. So, i want to hide Saturday and Sunday.

Is it possible ?

Thanks

**Comment by barbuslex** [comment]
Actually, I do it with this css : 

```css
.picker__table th:nth-child(6), .picker__table th:nth-child(7),
.picker__table td:nth-child(6), .picker__table td:nth-child(7) {
    display: none;
    visibility: hidden;
}
```
