### ISSUE TITLE
Keep picker persistently open

### ISSUE THREAD

**Issue by sympmarc** [amsul/pickadate.js#737]
I'd like to be able to use the picker as a way to filter calendar items by day. When the user clicks on a day, I show the events for that day, etc. 

Ideally, I don't want the picker to ever close; I want it persistently open on my page. I can't figure out anything in the API or by using CSS which will make this work. There's some registration on the blur event for the picker frame, but I can't seem to track it down. Is this possible?

**Comment by kavadas** [comment]
@sympmarc 

You can achieve what you want using some CSS code like the following:
```css
.picker {
  position: static;
}
.picker__holder {
  max-height: 1000px;
  position: static;
  transform: none;
  transition: none;
  opacity: 1;
  outline: none;
  border: none;
  box-shadow: none;
}
```

Keep in mind that:

1. This is very basic code. It has not been tested extensively and might not work as expected.
2. This has accessibility issues. The calendar remains open but the aria attributes are not updated properly. 

@amsul 
The ideal solution would be adding an option in the plugin to disable closing on blur.
